[package]
name = "rek"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.3"

[workspace]
members = [
  "rek-dsp",
  "rek-utils",
  "rek-folders/rek-shots",
  "rek-folders/rek-loops",
  "rek-folders/rek-stems",
  "rek-folders/rek-tracks",
]
